title: Mark Penhall Golf Lessons
description: Sharpen Your Skills with a Seasoned Golfer
baseurl: "" # Leave blank for GitHub Pages root
url: "https://markpenhallgolflessons.co.za" # Your custom domain
markdown: kramdown
